### ISSUE TITLE
Safe conduct to-do list

### ISSUE THREAD

**Issue by DanielMateosLab** [DanielMateosLab/documentos-los-guindales#1]
- [x] The form will have as title the name and dates of the event.
- [x] I want to have a form with the fields "Name", "DNI/NIE" and "email".
- [ ] I want the submit button to send a filled safe-conduct PDF to the given email.
- [ ] I want the submit button to save the users to whom the safe-conduct has already been sent.
- [ ] I want a table showing the users to whom the safe-conduct has been sent and the ammount of times, with the options to edit the user or re-send the email. It should have a column with the last email-message sent-date.
- [ ] I want the Name and NIE field to make a fetch to the sent safe-conducts on every key stroke. A warning will be displayed if both imput emails match.

**Comment by DanielMateosLab** [comment]
Use a Material UI table for the sent-emails table

**Comment by DanielMateosLab** [comment]
Before sending the PDF to the email, the PDF generation can be tested just opening a new tab with the PDF after clicking the submit button

**Comment by DanielMateosLab** [comment]
> Before sending the PDF to the email, the PDF generation can be tested just opening a new tab with the PDF after clicking the submit button

To mantain this functionality, we could send to the email or just export the pdf using query parameters like exportToPdf, or sendToMail
